# This is a basic workflow to help you get started with Actions

name: run_tests

# Controls when the workflow will run
on
 
          
          name: Tests
on: [push]
 jobs:
 runs-on: ubuntu-latest
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      name: Checkout repo
      uses: actions/checkout@v3
      # Runs a single command usi
      run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      name2: requirements
      run2: pip install -r requirements.txt
      name3: run tests
      run3: python -m unittest tests/test_extract_dataframe.py
      name4: status
      run4: echo "ğŸ This job's status is ${{ job.status }}."
          
          
          
        
         
